version: "3"

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data:/root/db
  app: 
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app