services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  app: 
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app